/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eugen_mymusic_PlayCtrl */

#ifndef _Included_eugen_mymusic_PlayCtrl
#define _Included_eugen_mymusic_PlayCtrl
#ifdef __cplusplus
extern "C" {
#endif
#undef eugen_mymusic_PlayCtrl_MODE_PRIVATE
#define eugen_mymusic_PlayCtrl_MODE_PRIVATE 0L
#undef eugen_mymusic_PlayCtrl_MODE_WORLD_READABLE
#define eugen_mymusic_PlayCtrl_MODE_WORLD_READABLE 1L
#undef eugen_mymusic_PlayCtrl_MODE_WORLD_WRITEABLE
#define eugen_mymusic_PlayCtrl_MODE_WORLD_WRITEABLE 2L
#undef eugen_mymusic_PlayCtrl_MODE_APPEND
#define eugen_mymusic_PlayCtrl_MODE_APPEND 32768L
#undef eugen_mymusic_PlayCtrl_MODE_MULTI_PROCESS
#define eugen_mymusic_PlayCtrl_MODE_MULTI_PROCESS 4L
#undef eugen_mymusic_PlayCtrl_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define eugen_mymusic_PlayCtrl_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef eugen_mymusic_PlayCtrl_BIND_AUTO_CREATE
#define eugen_mymusic_PlayCtrl_BIND_AUTO_CREATE 1L
#undef eugen_mymusic_PlayCtrl_BIND_DEBUG_UNBIND
#define eugen_mymusic_PlayCtrl_BIND_DEBUG_UNBIND 2L
#undef eugen_mymusic_PlayCtrl_BIND_NOT_FOREGROUND
#define eugen_mymusic_PlayCtrl_BIND_NOT_FOREGROUND 4L
#undef eugen_mymusic_PlayCtrl_BIND_ABOVE_CLIENT
#define eugen_mymusic_PlayCtrl_BIND_ABOVE_CLIENT 8L
#undef eugen_mymusic_PlayCtrl_BIND_ALLOW_OOM_MANAGEMENT
#define eugen_mymusic_PlayCtrl_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef eugen_mymusic_PlayCtrl_BIND_WAIVE_PRIORITY
#define eugen_mymusic_PlayCtrl_BIND_WAIVE_PRIORITY 32L
#undef eugen_mymusic_PlayCtrl_BIND_IMPORTANT
#define eugen_mymusic_PlayCtrl_BIND_IMPORTANT 64L
#undef eugen_mymusic_PlayCtrl_BIND_ADJUST_WITH_ACTIVITY
#define eugen_mymusic_PlayCtrl_BIND_ADJUST_WITH_ACTIVITY 128L
#undef eugen_mymusic_PlayCtrl_CONTEXT_INCLUDE_CODE
#define eugen_mymusic_PlayCtrl_CONTEXT_INCLUDE_CODE 1L
#undef eugen_mymusic_PlayCtrl_CONTEXT_IGNORE_SECURITY
#define eugen_mymusic_PlayCtrl_CONTEXT_IGNORE_SECURITY 2L
#undef eugen_mymusic_PlayCtrl_CONTEXT_RESTRICTED
#define eugen_mymusic_PlayCtrl_CONTEXT_RESTRICTED 4L
#undef eugen_mymusic_PlayCtrl_RESULT_CANCELED
#define eugen_mymusic_PlayCtrl_RESULT_CANCELED 0L
#undef eugen_mymusic_PlayCtrl_RESULT_OK
#define eugen_mymusic_PlayCtrl_RESULT_OK -1L
#undef eugen_mymusic_PlayCtrl_RESULT_FIRST_USER
#define eugen_mymusic_PlayCtrl_RESULT_FIRST_USER 1L
#undef eugen_mymusic_PlayCtrl_DEFAULT_KEYS_DISABLE
#define eugen_mymusic_PlayCtrl_DEFAULT_KEYS_DISABLE 0L
#undef eugen_mymusic_PlayCtrl_DEFAULT_KEYS_DIALER
#define eugen_mymusic_PlayCtrl_DEFAULT_KEYS_DIALER 1L
#undef eugen_mymusic_PlayCtrl_DEFAULT_KEYS_SHORTCUT
#define eugen_mymusic_PlayCtrl_DEFAULT_KEYS_SHORTCUT 2L
#undef eugen_mymusic_PlayCtrl_DEFAULT_KEYS_SEARCH_LOCAL
#define eugen_mymusic_PlayCtrl_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef eugen_mymusic_PlayCtrl_DEFAULT_KEYS_SEARCH_GLOBAL
#define eugen_mymusic_PlayCtrl_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    setStateStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_setStateStart
  (JNIEnv *, jobject);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    setStateStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_setStateStop
  (JNIEnv *, jobject);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    setStateDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_setStateDestroy
  (JNIEnv *, jobject);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_main
  (JNIEnv *, jobject);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    updateSoundSystem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_updateSoundSystem
  (JNIEnv *, jobject);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    playSound
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eugen_mymusic_PlayCtrl_playSound
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    stopSound
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_eugen_mymusic_PlayCtrl_stopSound
  (JNIEnv *, jobject, jint);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    pauseSound
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_pauseSound
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    isSoundPaused
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_eugen_mymusic_PlayCtrl_isSoundPaused
  (JNIEnv *, jobject, jint);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    getSoundPos
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_eugen_mymusic_PlayCtrl_getSoundPos
  (JNIEnv *, jobject, jint);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    getSoundDur
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_eugen_mymusic_PlayCtrl_getSoundDur
  (JNIEnv *, jobject, jint);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    setSoundPos
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_setSoundPos
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    setSoundVol
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_setSoundVol
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    setSoundSpd
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_setSoundSpd
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    setSoundLoopPoint
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_setSoundLoopPoint
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    setSoundLoopCount
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_setSoundLoopCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    setSoundLooped
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_eugen_mymusic_PlayCtrl_setSoundLooped
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     eugen_mymusic_PlayCtrl
 * Method:    getSoundLooped
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_eugen_mymusic_PlayCtrl_getSoundLooped
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
