/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eugen_mymusic_PlayCtrl_ABInfo */

#ifndef _Included_eugen_mymusic_PlayCtrl_ABInfo
#define _Included_eugen_mymusic_PlayCtrl_ABInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
