/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eugen_mymusic_PlayCtrl_ABState */

#ifndef _Included_eugen_mymusic_PlayCtrl_ABState
#define _Included_eugen_mymusic_PlayCtrl_ABState
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
